apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-service-prometheus
  namespace: istio-system
  annotations:
    admiral.io/env: eks
  labels:
    identity: prometheus-eks
spec:
  policy:
    - dnsPrefix: default
      lbType: 0
