apiVersion: v1
kind: Namespace
metadata:
  annotations: null
  labels:
    istio-injection: disabled
  name: admiral-sync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admiral
  namespace: admiral-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-sync-write
  namespace: admiral-sync
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  - serviceentries
  - gateways
  verbs:
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admiral-sidecar-write
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - sidecars
  verbs:
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admiral-sync-read
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - services
  - nodes
  - deployments
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  - serviceentries
  - envoyfilters
  - gateways
  - sidecars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admiral.io
  resources:
  - globaltrafficpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: istio-admin
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  - serviceentries
  - envoyfilters
  - gateways
  - sidecars
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: istio-viewers
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  - serviceentries
  - envoyfilters
  - gateways
  - sidecars
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-sync-write-binding
  namespace: admiral-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-sync-write
subjects:
- kind: ServiceAccount
  name: admiral
  namespace: admiral-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admiral-sidecar-write-binding
  namespace: admiral-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admiral-sidecar-write
subjects:
- kind: ServiceAccount
  name: admiral
  namespace: admiral-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admiral-sync-read-binding
  namespace: admiral-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admiral-sync-read
subjects:
- kind: ServiceAccount
  name: admiral
  namespace: admiral-sync
