apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: admiral
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: admiral
  name: admiral
  namespace: admiral
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-configmap-role
  namespace: admiral-sync
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-dependency-role
  namespace: admiral
rules:
- apiGroups:
  - admiral.io
  resources:
  - dependencies
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-secret-role
  namespace: admiral
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-configmap-role-binding
  namespace: admiral-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-configmap-role
subjects:
- kind: ServiceAccount
  name: admiral
  namespace: admiral
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-dependency-role-binding
  namespace: admiral
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-dependency-role
subjects:
- kind: ServiceAccount
  name: admiral
  namespace: admiral
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-secret-role-binding
  namespace: admiral
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-secret-role
subjects:
- kind: ServiceAccount
  name: admiral
  namespace: admiral
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admiral
  name: admiral
  namespace: admiral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admiral
  template:
    metadata:
      labels:
        app: admiral
    spec:
      containers:
      - args:
        - --dependency_namespace
        - admiral
        - --secret_namespace
        - admiral
        - --sync_namespace
        - admiral-sync
        - --sync_period
        - 10s
        - --gateway_app
        - istio-eastwestgateway
        image: docker.io/admiralproj/admiral:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: admiral
        ports:
        - containerPort: 8080
          name: service
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 2048M
          requests:
            cpu: 0.25
            memory: 256M
      serviceAccountName: admiral
